name: 01 - prueba

on:
  push:
    branches: [main]

jobs:
  tareaUno:
    runs-on: ubuntu-22.04
    steps:
      - name: Saludar
        run: echo "Intento numero de 2 de Git action"

      - name: Ver fechas del runner
        run: date

  descargar-repo:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v6